---
ModelName : MAR_RESNET18_PADDED_256_lab_train

PathSave : Models/outputs/

CheckpointName : checkpoint.pt

Train : 
  - lab/train_mar_0.csv
  - lab/train_mar_1.csv
  - lab/train_mar_2.csv
Test :
  - lab/test_mar_0.csv
  - lab/test_mar_1.csv
  - lab/test_mar_2.csv

CheckpointFreq : 5

NEpochs : 100

BatchSize : 32

Seed : 0

Model :
  Layers :
    - 2
    - 2
    - 2
    - 2
  OutClasses : 5
  Channels : 1

TransformTrain:
  ToRGB :
    num_output_channels : 3
  ColorJitter:
    brightness : 0.5
  ToGrayscale :
    num_output_channels : 1
  Padding :
    out_shape : 256
  VerticalFlip: 
    p : 0.5
  HorizontalFlip : 
    p : 0.5
  Rotation : 
    min : -90
    max : 90

TransformTest:
  Padding : 
    out_shape : 256
 
Optimizer : 
  lr : 0.001
  weight_decay : 0.000001

Scheduler :
  gamma : 0.95

