---
ModelName : MAR_RESNET34_RESIZED_256_ALL

PathSave : Models/outputs/

LoadPath : Dataset/train_mar.csv

CheckpointName : checkpoint.pt

CheckpointFreq : 5

NSamples : 1000

NEpochs : 200

BatchSize : 32

KFold : 5

Seed : 0

Model :
  Layers :
    - 3
    - 4
    - 6
    - 3
  OutClasses : 5
  Channels : 1

TransformTrain:
  VerticalFlip: 
    p : 0.5
  HorizontalFlip : 
    p : 0.5
  Rotation : 
    min : -90
    max : 90
  Resize :
    width : 256
    height : 256

TransformTest:
  Resize :
    width : 256
    height : 256
 
Optimizer : 
  lr : 0.001
  weight_decay : 0.000001

Scheduler :
  gamma : 0.95
