---
ModelName : Test_Data_Augmentation

PathSave : Models/outputs/

LoadPath : Dataset/train_mar.csv

CheckpointName : checkpoint.pt

CheckpointFreq : 5

NSamples : 10

NEpochs : 50

BatchSize : 4

TrainTestSplit : 0.95

KFold : 5

Seed : 0

Model :
  Layers :
    - 3
    - 4
    - 6
    - 3
  OutClasses : 5
  Channels : 1

TransformTrain:
  Padding :
    out_shape : 64
  VerticalFlip: 
    p : 0.5
  HorizontalFlip : 
    p : 0.5
  Rotation : 
    min : -90
    max : 90


TransformTest:
  Padding : 
    out_shape : 64
 
Optimizer : 
  lr : 0.001
  weight_decay : 0.000001

Scheduler :
  gamma : 0.95
