---
ModelName : Test_Data_Augmentation

PathSave : Models/outputs/

LoadPath : Dataset/train_bbox.csv

CheckpointName : checkpoint.pt

CheckpointFreq : 5

NSamples : 20

NEpochs : 10

BatchSize : 4

KFold : 5

Seed : 0

TransformTrain:
  VerticalFlip: 
    p : 0.5
  HorizontalFlip : 
    p : 0.5
  Rotation : 
    min : -90
    max : 90
  Resize :
    width : 256
    height : 256

TransformTest:
  Resize :
    width : 256
    height : 256
 
Optimizer : 
  lr : 0.001
  weight_decay : 0.000001
Scheduler :
  gamma : 0.95
